# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tech-challenge-ss' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tech-challenge-ss
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'

  target 'tech-challenge-ssTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'tech-challenge-ssUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
